// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_log.proto

package com.DataStream.protoPojo;

public interface EventLogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.EventLog)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>uint64 timestamp = 2;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>string event_id = 50;</code>
   * @return The eventId.
   */
  java.lang.String getEventId();
  /**
   * <code>string event_id = 50;</code>
   * @return The bytes for eventId.
   */
  com.google.protobuf.ByteString
      getEventIdBytes();

  /**
   * <code>string event_name = 53;</code>
   * @return The eventName.
   */
  java.lang.String getEventName();
  /**
   * <code>string event_name = 53;</code>
   * @return The bytes for eventName.
   */
  com.google.protobuf.ByteString
      getEventNameBytes();
}
