// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_log.proto

package com.DataStream.protoPojo;

public final class EventLogProto {
  private EventLogProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_EventLog_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_EventLog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017event_log.proto\022\003com\"W\n\010EventLog\022\022\n\nre" +
      "quest_id\030\001 \001(\t\022\021\n\ttimestamp\030\002 \001(\004\022\020\n\010eve" +
      "nt_id\0302 \001(\t\022\022\n\nevent_name\0305 \001(\tB+\n\030com.D" +
      "ataStream.protoPojoB\rEventLogProtoP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_EventLog_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_EventLog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_EventLog_descriptor,
        new java.lang.String[] { "RequestId", "Timestamp", "EventId", "EventName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
